### ISSUE TITLE
fix 500 Data Structures and Algorithms link

### ISSUE THREAD

**Issue by kens-visuals** [danieldelcore/mega-interview-guide#20]
Hi, I realized that the link for '500 Data Structures and Algorithms' is broken, I tried to fork the repo and change it, but GitHub was lagging. Anyway, here's the working link, (https://techiedelight.quora.com/500-Data-Structures-and-Algorithms-interview-questions-and-their-solutions)

P.S. Nice repo by the way 👌🏻

**Comment by danieldelcore** [comment]
Oh thanks for the heads up! I'll push that up now! 

Glad you like the repo!

**Comment by danieldelcore** [comment]
Should be up now! Thanks again!
