### ISSUE TITLE
Answers and implementation examples should be in expandable sections

### ISSUE THREAD

**Issue by danieldelcore** [danieldelcore/mega-interview-guide#3]
https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab

**Comment by msmfa** [comment]
Hi Daniel. Can I take this?

**Comment by danieldelcore** [comment]
@msmfa, absolutely! Feel free to give it a go!

**Comment by msmfa** [comment]
Thanks Daniel. Could you confirm which sections should be expandable? Is it just the answers to the 'Questions' section?

**Comment by danieldelcore** [comment]
Yeah that's right :) 

Everything after the `Answer:` text. 

That would be fantastic - thanks!

**Comment by danieldelcore** [comment]
Maybe we could even just match something like:

![image](https://user-images.githubusercontent.com/3030010/82538303-e5b92980-9b8e-11ea-9cd1-cbdf78e27ebc.png)

**Comment by msmfa** [comment]
Cool. I'm on it!
