### ISSUE TITLE
We need a website!

### ISSUE THREAD

**Issue by danieldelcore** [danieldelcore/mega-interview-guide#8]

**Comment by zainafzal08** [comment]
A cheeky trick i've used before is to set up github.io to serve the repo root and then have an index.html file grab the readme, compile it, dump the html output and then style it up nice. 

It's pretty good as a starting place, chucked up a PR (https://github.com/danieldelcore/mega-interview-guide/pull/13) which does it for this repo, check it out! (could def use some more css love though :p )

![image](https://user-images.githubusercontent.com/12245732/113689853-1a35c580-970e-11eb-8a0d-ee256ecfd486.png)

![image](https://user-images.githubusercontent.com/12245732/113689925-2f125900-970e-11eb-95a2-8181fe6bbf12.png)

**Comment by danieldelcore** [comment]
Legend!!! Closing this for now! Will deploy your pr live now

**Comment by danieldelcore** [comment]
WORKING YAY! https://danieldelcore.github.io/mega-interview-guide/

**Comment by zainafzal08** [comment]
\o/ Woo!
